version: '3.5'
services:
  api01: &api
    build: .
    hostname: api01
    network_mode: host
    container_name: api01-phoenix
    environment:
      - PHX_HOST=api01
      - DATABASE_URL=postgres://docker:docker@localhost:5432/rinha
      - CREATE_TABLE=true
      - SECRET_KEY_BASE=Hy7pQWVbcnpz7w45pawgl5aqG7HdyDHiXQh/dGQN0bVDCKIPKd4D1aiN3v24F0Jg
    ports:
      - "4000:4000"
    depends_on:
      - postgres

    # deploy:
      # resources:
        # limits:
          # cpus: '0.5'
          # memory: '150MB'

  api02:
    <<: *api
    hostname: api02
    network_mode: host
    container_name: api02-phoenix
    environment:
      - PHX_HOST=api02
      - DATABASE_URL=postgres://docker:docker@localhost:5432/rinha
      - CREATE_TABLE=false
      - SECRET_KEY_BASE=Hy7pQWVbcnpz7w45pawgl5aqG7HdyDHiXQh/dGQN0bVDCKIPKd4D1aiN3v24F0Jg
    ports:
      - "4001:4001"

  postgres:
    image: postgres:16.1-alpine3.19
    network_mode: host
    container_name: postgres
    # command: postgres -c 'max_connections=75' -c 'log_error_verbosity=terse'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.4'
    #       memory: '200MB'

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: '50MB'